CORE_DIR           = $(ROOT_DIR)
LIBRETRO_COMM_DIR  = $(ROOT_DIR)/deps/libretro-common
RSPDIR_PARALLEL    =  $(CORE_DIR)/src/device/rcp/rsp/p_rsp

DYNAREC_USED := 0

INCFLAGS += \
	-I$(ROOT_DIR)/deps \
	-I$(ROOT_DIR)/custom \
	-I$(ROOT_DIR)/custom/osal \
	-I$(CORE_DIR)/src \
	-I$(CORE_DIR)/src/api \
	-I$(LIBRETRO_COMM_DIR)/include \
	-I$(CORE_DIR)/src/device/rcp/rdp

ifneq (,$(findstring win,$(platform)))
	INCFLAGS += -I$(ROOT_DIR)/deps/mman
endif

SOURCES_C = \
	$(CORE_DIR)/src/api/callbacks.c \
	$(ROOT_DIR)/src/api/config.c \
	$(CORE_DIR)/src/api/frontend.c \
	$(CORE_DIR)/src/backends/plugins_compat/audio_plugin_compat.c \
	$(CORE_DIR)/src/backends/api/video_capture_backend.c \
	$(CORE_DIR)/src/backends/plugins_compat/input_plugin_compat.c \
	$(CORE_DIR)/src/backends/clock_ctime_plus_delta.c \
	$(CORE_DIR)/src/backends/dummy_video_capture.c \
	$(CORE_DIR)/src/backends/file_storage.c \
	$(CORE_DIR)/src/device/cart/cart.c \
	$(CORE_DIR)/src/device/cart/af_rtc.c \
	$(CORE_DIR)/src/device/cart/cart_rom.c \
	$(CORE_DIR)/src/device/cart/eeprom.c \
	$(CORE_DIR)/src/device/cart/flashram.c \
	$(CORE_DIR)/src/device/cart/is_viewer.c \
	$(CORE_DIR)/src/device/cart/sram.c \
	$(CORE_DIR)/src/device/controllers/game_controller.c \
	$(CORE_DIR)/src/device/controllers/paks/biopak.c \
	$(CORE_DIR)/src/device/controllers/paks/mempak.c \
	$(CORE_DIR)/src/device/controllers/paks/rumblepak.c \
	$(CORE_DIR)/src/device/controllers/paks/transferpak.c \
	$(CORE_DIR)/src/device/dd_controller.c \
	$(CORE_DIR)/src/device/disk.c \
	$(CORE_DIR)/src/device/device.c \
	$(CORE_DIR)/src/device/gb/gb_cart.c \
	$(CORE_DIR)/src/device/gb/mbc3_rtc.c \
	$(CORE_DIR)/src/device/gb/m64282fp.c \
	$(CORE_DIR)/src/device/memory.c \
	$(CORE_DIR)/src/device/pif/bootrom_hle.c \
	$(CORE_DIR)/src/device/pif/cic.c \
	$(CORE_DIR)/src/device/pif/n64_cic_nus_6105.c \
	$(CORE_DIR)/src/device/pif/pif.c \
	$(CORE_DIR)/src/device/r4300/cp0.c \
	$(CORE_DIR)/src/device/r4300/cached_interp.c \
	$(CORE_DIR)/src/device/r4300/cp1.c \
	$(CORE_DIR)/src/device/r4300/fpu_native.c \
	$(CORE_DIR)/src/device/r4300/idec.c \
	$(CORE_DIR)/src/device/r4300/interrupt.c \
	$(CORE_DIR)/src/device/r4300/pure_interp.c \
	$(CORE_DIR)/src/device/r4300/r4300_core.c \
	$(CORE_DIR)/src/device/r4300/tlb.c \
	$(CORE_DIR)/src/device/rcp/ai_controller.c \
	$(CORE_DIR)/src/device/rcp/mi_controller.c \
	$(CORE_DIR)/src/device/rcp/pi_controller.c \
	$(CORE_DIR)/src/device/rcp/rdp/fb.c \
	$(CORE_DIR)/src/device/rcp/rdp/rdp_core.c \
	$(CORE_DIR)/src/device/rcp/ri_controller.c \
	$(CORE_DIR)/src/device/rcp/rsp/rsp_core.c \
	$(CORE_DIR)/src/device/rcp/si_controller.c \
	$(CORE_DIR)/src/device/rcp/rdp/vi_controller.c \
	$(CORE_DIR)/src/device/rdram.c \
	$(CORE_DIR)/src/main/main.c \
	$(CORE_DIR)/src/main/savestates.c \
	$(CORE_DIR)/src/main/util.c \
	$(CORE_DIR)/src/main/rom.c \
	$(CORE_DIR)/src/plugin/plugin.c 


ANGRYLION_DIR = $(CORE_DIR)/src/device/rcp/rdp/angrylion
RSP_HLE_DIR = $(CORE_DIR)/src/device/rcp/rsp/hle
SOURCES_C += $(wildcard $(RSP_HLE_DIR)/*.c) \
             $(wildcard $(ANGRYLION_DIR)/rdp_emit*.c) \
             $(CORE_DIR)/src/device/rcp/rsp/optional_rsp.c
SOURCES_C += $(LIBRETRO_COMM_DIR)/encodings/encoding_crc32.c
SOURCES_C += $(CORE_DIR)/src/renderer_options.c \
             $(CORE_DIR)/src/device/rcp/rdp/performance_cores.c
SOURCES_C += $(ANGRYLION_DIR)/n64video.c \
             $(ANGRYLION_DIR)/parallel_al.c \
             $(ANGRYLION_DIR)/output.c \
             $(LIBRETRO_COMM_DIR)/rthreads/rthreads.c
# Keep the software rasterizer optimized in debug builds.
$(ANGRYLION_DIR)/n64video.o $(ANGRYLION_DIR)/parallel_al.o: CFLAGS += -O3
$(ANGRYLION_DIR)/parallel_al.o: $(CORE_DIR)/src/device/rcp/rdp/performance_cores.h
$(CORE_DIR)/src/libretro.o: $(CORE_DIR)/src/renderer_options.h
$(CORE_DIR)/src/renderer_options.o: $(CORE_DIR)/src/renderer_options.h
$(CORE_DIR)/src/device/rcp/rdp/performance_cores.o: $(CORE_DIR)/src/device/rcp/rdp/performance_cores.h
$(ANGRYLION_DIR)/n64video.o: $(wildcard $(ANGRYLION_DIR)/*.h $(ANGRYLION_DIR)/n64video/*.c $(ANGRYLION_DIR)/n64video/rdp/* $(ANGRYLION_DIR)/n64video/vi/*)

ifeq ($(HAVE_PARALLEL_RDP),1)
PARALLEL_RDP_IMPLEMENTATION = $(CORE_DIR)/src/device/rcp/rdp/p_rdp
include $(PARALLEL_RDP_IMPLEMENTATION)/config.mk
CFLAGS += $(PARALLEL_RDP_CFLAGS) -DHAVE_PARALLEL_RDP
CXXFLAGS += $(PARALLEL_RDP_CXXFLAGS) $(PARALLEL_RDP_INCLUDE_DIRS) -DHAVE_PARALLEL_RDP -DHAVE_RENDERER_AFFINITY
INCFLAGS += -I$(PARALLEL_RDP_IMPLEMENTATION)/vulkan-headers/include
SOURCES_C += $(PARALLEL_RDP_SOURCES_C)
SOURCES_CXX += $(PARALLEL_RDP_SOURCES_CXX) $(CORE_DIR)/src/device/rcp/rdp/parallel_imp.cpp
LDFLAGS += $(PARALLEL_RDP_LDFLAGS)
$(PARALLEL_RDP_IMPLEMENTATION)/parallel-rdp/rdp_device.o: $(PARALLEL_RDP_IMPLEMENTATION)/parallel-rdp/worker_thread.hpp $(CORE_DIR)/src/device/rcp/rdp/performance_cores.h
$(PARALLEL_RDP_IMPLEMENTATION)/parallel-rdp/command_ring.o: $(CORE_DIR)/src/device/rcp/rdp/performance_cores.h
$(CORE_DIR)/src/device/rcp/rdp/parallel_imp.o: $(CORE_DIR)/src/renderer_options.h $(CORE_DIR)/src/device/rcp/rdp/performance_cores.h
endif

# MD5 lib
SOURCES_C += \
	$(ROOT_DIR)/deps/md5.c
COREFLAGS += -I$(ROOT_DIR)/deps/md5


ifneq (,$(findstring win,$(platform)))
	SOURCES_C += $(ROOT_DIR)/custom/osal/osal_files_win32.c
	SOURCES_C += $(ROOT_DIR)/deps/mman/sys/mman.c
else
	SOURCES_C += $(ROOT_DIR)/custom/osal/osal_files_unix.c
endif

# Libretro
SOURCES_C += $(ROOT_DIR)/src/libretro.c \
	$(LIBRETRO_COMM_DIR)/memmap/memalign.c \
	$(ROOT_DIR)/src/plugin/emulate_game_controller_via_libretro.c \
	$(LIBRETRO_COMM_DIR)/audio/resampler/drivers/sinc_resampler.c \
	$(LIBRETRO_COMM_DIR)/audio/resampler/drivers/nearest_resampler.c \
	$(LIBRETRO_COMM_DIR)/audio/resampler/audio_resampler.c \
	$(ROOT_DIR)/src/plugin/audio_backend_libretro.c \
	$(LIBRETRO_COMM_DIR)/file/config_file.c \
	$(LIBRETRO_COMM_DIR)/file/config_file_userdata.c \
	$(LIBRETRO_COMM_DIR)/file/file_path.c \
	$(LIBRETRO_COMM_DIR)/file/file_path_io.c \
	$(LIBRETRO_COMM_DIR)/time/rtime.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c \
	$(LIBRETRO_COMM_DIR)/audio/conversion/float_to_s16.c \
	$(LIBRETRO_COMM_DIR)/audio/conversion/s16_to_float.c \
	$(LIBRETRO_COMM_DIR)/features/features_cpu.c \
	$(LIBRETRO_COMM_DIR)/lists/string_list.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
	$(LIBRETRO_COMM_DIR)/string/stdstring.c \
	$(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c \
	$(LIBRETRO_COMM_DIR)/streams/file_stream.c \
	$(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
	$(ROOT_DIR)/src/api/vidext_libretro.c \


	PARALLEL_RSP_ARCH := simd
	SOURCES_CXX += $(RSPDIR_PARALLEL)/parallel.cpp \
				   $(RSPDIR_PARALLEL)/rsp_disasm.cpp \
				   $(RSPDIR_PARALLEL)/jit_allocator.cpp \
				   $(wildcard $(RSPDIR_PARALLEL)/rsp/*.cpp) \
				   $(wildcard $(RSPDIR_PARALLEL)/arch/$(PARALLEL_RSP_ARCH)/rsp/*.cpp)
ifneq ($(DEBUG_JIT),)
	CXXFLAGS += -DDEBUG_JIT
	SOURCES_CXX += $(RSPDIR_PARALLEL)/debug_jit.cpp \
				   $(RSPDIR_PARALLEL)/rsp.cpp
	LDFLAGS += -ldl
else
	SOURCES_CXX += $(RSPDIR_PARALLEL)/rsp_jit.cpp
	SOURCES_C += \
				 $(RSPDIR_PARALLEL)/lightning/lib/jit_disasm.c \
				 $(RSPDIR_PARALLEL)/lightning/lib/jit_memory.c \
				 $(RSPDIR_PARALLEL)/lightning/lib/jit_names.c \
				 $(RSPDIR_PARALLEL)/lightning/lib/jit_note.c \
				 $(RSPDIR_PARALLEL)/lightning/lib/jit_print.c \
				 $(RSPDIR_PARALLEL)/lightning/lib/jit_size.c \
				 $(RSPDIR_PARALLEL)/lightning/lib/lightning.c
endif

	CXXFLAGS += -I$(RSPDIR_PARALLEL)/arch/$(PARALLEL_RSP_ARCH)/rsp -I$(RSPDIR_PARALLEL)/lightning/include
	CFLAGS += -DHAVE_PARALLEL_RSP -DPARALLEL_INTEGRATION -I$(RSPDIR_PARALLEL)/lightning/include
	CXXFLAGS += -DHAVE_PARALLEL_RSP -DPARALLEL_INTEGRATION

ifeq ($(HAVE_NEON),1)
	SOURCES_ASM += $(LIBRETRO_COMM_DIR)/audio/conversion/float_to_s16_neon.S \
						$(LIBRETRO_COMM_DIR)/audio/conversion/s16_to_float_neon.S \
						$(LIBRETRO_COMM_DIR)/audio/resampler/drivers/sinc_resampler_neon.S
endif
